# UFW setup

- name: Allow ssh traffic
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Allow tcp traffic port 8080
  ufw:
    rule: allow
    from_ip: 35.177.0.107
    port: 8080
    proto: tcp

- name: Allow tcp traffic port 8081
  ufw:
    rule: allow
    from_ip: 35.177.0.107
    port: 8081
    proto: tcp

- name: Enable firewall
  ufw:
    state: enabled
    policy: deny
    direction: incoming

# Setup packages
- name: Install pip
  apt:
    update_cache: yes
    name: python3-pip

- name: Install required system packages
  apt:
    name:
      [
        "apt-transport-https",
        "ca-certificates",
        "curl",
        "ca-certificates",
        "curl",
        "software-properties-common",
        "python3-pip",
        "virtualenv",
        "python3-setuptools",
      ]
    state: latest

- name: Add Dokcer GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: install docker-py
  pip: name=docker-py

- name: enable Docker services
  service:
    name: "docker"
    state: started
    enabled: yes

- name: Check if container is running
  shell: docker ps

# - name: run docker image validator fontend
#   shell: docker run -dit --name validator-frontend -p 8081:8081 thepsalmist/validator-frontend-image:v1

- name: show running images
  shell: docker images
