# UFW setup

- name: Allow ssh traffic
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Allow http traffic port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow https traffic port 443
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Enable firewall
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Ensure Nginx is installed and it is the latest version
  apt:
    name: nginx
    state: latest
  become: yes

- name: Start Nginx
  service:
    name: nginx
    state: started
  become: yes

- name: Copy the Nginx config file and restart nginx
  copy:
    src: nginx.cfg
    dest: /etc/nginx/sites-available/nginx.cfg
  become: yes

- name: Create symlink
  file:
    src: /etc/nginx/sites-available/nginx.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
